### Post 'Hello!"
POST http://localhost:8080/messages
Content-Type: application/json

{
  "id" : "5146",
  "text": "Hello!"
}

### Post "Bonjour!"

POST http://localhost:8080/messages
Content-Type: application/json

{
  "id" : "54",
  "text": "Bonjour!"
}

### Post "Privet!"

POST http://localhost:8080/messages
Content-Type: application/json

{
  "id" : "1452",
  "text": "Privet!"
}

### Get all the messages
GET http://localhost:8080/messages/1452
